# Generated by Django 6.0.2 on 2026-06-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='local',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
