# Generated by Django 6.0.2 on 2026-05-13 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_age'),
        ('products', '0002_category_alter_brand_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_selles', to='accounts.profile'),
        ),
    ]
